"""Added user info

Revision ID: dc7ec8df31f7
Revises: ec989f90d2ca
Create Date: 2026-04-19 22:27:47.595100

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc7ec8df31f7"
down_revision: Union[str, Sequence[str], None] = "ec989f90d2ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("display_name", sa.String(length=100), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(length=255), nullable=False))
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.create_index(op.f("ix_users_display_name"), "users", ["display_name"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_display_name"), table_name="users")
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=True)
    op.drop_column("users", "password")
    op.drop_column("users", "display_name")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
