services:
  db:
    image: postgres:15-alpine
    container_name: habit_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: g9439
      POSTGRES_DB: habit_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: habit_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        ollama serve &
        sleep 5
        echo "📥 Checking and pulling embedding model..."
        ollama pull nomic-embed-text
        wait

  api:
    build: 
      context: ./api
    container_name: habit_api
    restart: always
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env_docker
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/app/chroma_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started

  ui:
    build: 
      context: ./ui
    container_name: habit_ui
    restart: always
    env_file:
      - .env_docker
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  pgdata:
  chromadb_data:
  ollama_models: